services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8888
      - API_KEY=an_api_key
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres?sslmode=disable
      - LOG_LEVEL=debug
    networks:
      - blog_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blog_network

volumes:
  postgres_data:

networks:
  blog_network:
    driver: bridge
