services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - PORT=8888
      - API_KEY=an_api_key
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres?sslmode=disable
      - LOG_LEVEL=debug

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
