version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - API_KEY=your_api_key_here
      - DATABASE_URL=postgres://postgres:password@db:5432/blogdb?sslmode=disable
      - LOG_LEVEL=info

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
