# fly.toml app configuration file generated for a-red-door-blog on 2024-09-28T17:25:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'a-red-door-blog'
primary_region = 'waw'

[env]
  LOG_LEVEL = 'info'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
