version: "3"

vars:
  NAME: blogserver
  TAG:
    sh: git rev-parse HEAD
  PORT: 8888
  TEMPL_VERSION: v0.2.778
  SQLC_VERSION: v1.27.0
  GOLANGCILINT_VERSION: v1.60.3

tasks:
  dep:
    desc: Install dependencies
    cmds:
      - npm install
      - go install github.com/a-h/templ/cmd/templ@{{.TEMPL_VERSION}}
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@{{.SQLC_VERSION}}
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCILINT_VERSION}}
      - go mod tidy

  assets:
    desc: Build tailwind assets
    cmds:
      - npx tailwindcss -i ./tailwind.css -o ./static/styles.css
    sources:
      - ./**/*.templ
      - ./tailwind.css
      - ./tailwind.config.js
    generates:
      - ./static/styles.css

  generate:
    desc: Code generation
    cmds:
      - go generate ./...
    sources:
      - ./**/*.templ
      - ./repository/sqlc/*.sql
    generates:
      - ./**/*_templ.go
      - ./repository/*_sqlc.go

  lint:
    desc: Run lint
    cmds:
      - golangci-lint run
    deps:
      - generate

  test:
    desc: Run tests
    cmds:
      - go test ./...
    deps:
      - assets
      # - lint

  run:
    desc: Run the app as a local server
    deps:
      - assets
      - generate
      - test
    cmds:
      - go run ./cmd/server/... --port {{.PORT}}

  docker-build:
    desc: Build the blogserver container using docker
    deps:
      - test
    cmds:
      - docker build . -t {{.NAME}}:{{.TAG}}

  docker-run:
    desc: Run the blogserver container using docker
    deps:
      - docker-build
    cmds:
      - docker run -p {{.PORT}} {{.NAME}}:{{.TAG}} --port {{.PORT}}
