CREATE TABLE articles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    thumbnail TEXT NOT NULL,
    slug VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    tags JSON,
    publication_date DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX idx_articles_tags ON articles ((CAST(tags AS CHAR(255))));
